spring:
  application:
    name: discovery-client
  cloud:
    zookeeper:
      enabled: false #zookeeper服务发现与注册失效(默认)
    consul:
      enabled: false # consul服务发现与注册失效(默认)
  mandatory-file-encoding: utf-8
  http:
    encoding:
      charset: UTF-8
      enabled: true
eureka:
  client:
    enabled: false # eureka服务发现与注册失效(默认)

logging:
  level:
    root: info
  file:
    max-size: 15MB
    path: logs
    name: discovery-client.log
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSS
server:
  port: 9091
  undertow:
    accesslog:
      enabled: true
      dir: undertow-access-logs
      pattern: common
      rotate: true
      prefix: discovery-client-access-log.
      suffix: log
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: true


--- # profile for eureka
spring:
  profiles: eureka
eureka:
  service:
    host: 127.0.0.1
    port: 8761
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${server.port}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka.service.host}:${eureka.service.port}/eureka/
    enabled: true

--- # profile for zookeeper
spring:
  profiles: zookeeper
  cloud:
    zookeeper:
      enabled: true
      connect-string: 127.0.0.1:2181

--- # profile for consul
spring:
  profiles: consul
  cloud:
    consul:
      discovery:
        enabled: true
        ip-address: 127.0.0.1
        port: 8500