spring:
  application:
    name: service-consumer
  cloud:
    zookeeper:
      enabled: true
      connect-string: 127.0.0.1:2181
  mandatory-file-encoding: utf-8
  http:
    encoding:
      charset: UTF-8
      enabled: true

logging:
  level:
    root: info
  file:
    max-size: 15MB
    name: service-consumer.log
    path: logs
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSS
server:
  port: 9092
  undertow:
    accesslog:
      enabled: true
      dir: undertow-access-logs
      pattern: common
      rotate: true
      prefix: service-consumer-access-log.
      suffix: log
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: true

feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  compression:
    request:
      enabled: true
    response:
      enabled: true
